services:
  dev-db:
    volumes:
      - podman_db_data:/var/lib/mysql

  doubtfire-api:
    image: localhost/ontrack-doubtfire-api:11.0-local
    volumes:
      - ../../doubtfire-api/:/doubtfire:z
      - ../data/tmp:/doubtfire/tmp:z
      - ../data/student-work:/student-work:z

  doubtfire-sidekiq:
    image: localhost/ontrack-doubtfire-api:11.0-local
    volumes:
      - ../../doubtfire-api/:/doubtfire:z
      - ../data/tmp:/doubtfire/tmp:z
      - ../data/student-work:/student-work:z

  doubtfire-web:
    image: localhost/ontrack-doubtfire-web:11.0-local
    userns_mode: "keep-id:uid=1000,gid=1000"
    security_opt:
      - label=disable
    command: /bin/bash -c 'npm install && npm start'
    volumes:
      - ../../doubtfire-web:/doubtfire-web
      - ./proxy.conf.docker.json:/doubtfire-web/proxy.conf.json:ro

volumes:
  podman_db_data:
