services:
  dev-db:
    container_name: ppi-live-dev-db

  redis-sidekiq:
    container_name: ppi-live-redis-sidekiq

  mailpit:
    container_name: ppi-live-mailpit
    ports: !override
      - "8125:8025"
      - "1125:1025"

  doubtfire-api:
    container_name: ppi-live-api
    image: ppi-live-doubtfire-api:20260823
    ports: !override
      - "3100:3000"
    environment:
      DF_DEV_DB_HOST: dev-db
      DF_TEST_DB_HOST: dev-db
      DF_PRODUCTION_DB_HOST: dev-db
      DF_REDIS_SIDEKIQ_URL: redis://redis-sidekiq:6379/0
      DF_SMTP_ADDRESS: mailpit
      DF_INSTITUTION_HOST: http://localhost:3100

  doubtfire-web:
    container_name: ppi-live-web
    image: ppi-live-doubtfire-web:20260823
    ports: !override
      - "4300:4200"
    volumes: !override
      - ../../doubtfire-web:/doubtfire-web
      - web_node_modules:/doubtfire-web/node_modules
      - ./proxy.conf.docker.json:/doubtfire-web/proxy.conf.json:ro
